GET http://localhost:8080/health
###

POST http://localhost:8080/accounts
Content-Type: application/json

{
  "name": "Mushlya",
  "email": "mushlya@luwlya.com",
  "password": "1234pass4321"
}

###
PATCH http://localhost:8080/accounts/ba431486-b77d-4eeb-ba88-fc2b583fa676
Content-Type: application/json

{
  "email": "luwlya@luwlya.com"
}
###
GET http://localhost:8080/accounts/ba431486-b77d-4eeb-ba88-fc2b583fa677

###
POST http://localhost:8080/notes
Content-Type: application/json

{
  "title": "MyNote",
  "text": "Test my Note",
  "tags": ["test", "Note"]
}