GET http://localhost:8080/health
###

POST http://localhost:8080/accounts
Content-Type: application/json

{
  "name": "Kuwa",
  "email": "kuku@luwlya.com",
  "password": "1234pass4321"
}

###
PATCH http://localhost:8080/accounts/ba431486-b77d-4eeb-ba88-fc2b583fa676
Content-Type: application/json

{
  "email": "luwlya12@luwlya.com"
}
###
GET http://localhost:8080/accounts/ba431486-b77d-4eeb-ba88-fc2b583fa676

###
POST http://localhost:8080/notes
Content-Type: application/json

{
  "authorId": "ba431486-b77d-4eeb-ba88-fc2b583fa676",
  "title": "Private1",
  "text": "Test my Private Note",
  "tags": [
    "test",
    "Note"
  ],
  "visibility": "PRIVATE"
}

###
GET http://localhost:8080/notes

###
GET http://localhost:8080/notes/308d2ec9-c8e3-4aac-b5cc-f46f63f89a64

###
PATCH http://localhost:8080/notes/e89d87e0-50e3-476a-a1ad-e04cca9d620a
Content-Type: application/json

{
  "title": "PrivateNote"
}

###
DELETE http://localhost:8080/notes/49b74f62-834c-4720-a005-b4cf8ae9fd17

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "luwlya12@luwlya.com",
  "password": "1234pass4321"
}
